name = "sixty-second-showdown"
main = "index.ts"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[[d1_databases]]
binding = "DB"
database_name = "showdown-db"
database_id = "dummy-id"
